const events = [
  {
    name: "TechSpark 2025",
    image: "https://amcec.edu.in/wp-content/uploads/2022/07/IEEE.jpeg",
    description: "A technology hackathon focusing on innovative software solutions.",
    venue: "ICAT Design and Media College, Bangalore",
    time: "10:00 AM - 6:00 PM",
    conductedBy: "Tech Society",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "Free",
    lastDateToRegister: "2025-01-20",
    eventDate: "2025-02-05",
    prize: "₹50,000 Cash Prize + Internship Opportunity",
    thingsGivenToParticipants: ["Certificate of Participation", "T-Shirts", "Goodie Bags"],
    about: "TechSpark 2025 is an innovative tech hackathon where developers, engineers, and tech enthusiasts come together to solve real-world problems and showcase their creativity."
  },
  {
    name: "Art Fiesta 2025",
    image: "https://cdn-az.allevents.in/events9/banners/5f5e8d972d99b879e5e86637f8a976160a365f4c62cf9bf3395aed8f6bfd289e-rimg-w1200-h675-dc1f4665-gmir?v=1728589379",
    description: "A creative art competition where participants can showcase their artistic skills.",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    venue: "National Art Gallery, Bangalore",
    time: "11:00 AM - 5:00 PM",
    conductedBy: "Art Lovers Association",
    entryFee: "₹200",
    lastDateToRegister: "2025-01-18",
    eventDate: "2025-02-01",
    prize: "₹10,000 Cash Prize + Art Supplies",
    thingsGivenToParticipants: ["Certificate", "Art Supplies Kit"],
    about: "Art Fiesta 2025 is an artistic celebration where participants can express their creativity through painting, drawing, sculpture, and other art forms."
  },
  {
    name: "Startup Pitch Fest",
    image: "https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/mobile_banner/659d840d2f97e_mega-startup-pitch-day-and-expo-24.png?d=700x400",
    description: "An event for aspiring entrepreneurs to pitch their ideas to investors.",
    venue: "Bangalore Tech Park",
    time: "9:00 AM - 4:00 PM",
    conductedBy: "Startup Network",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "₹500",
    lastDateToRegister: "2025-01-25",
    eventDate: "2025-02-10",
    prize: "Funding Opportunity + Incubation Support",
    thingsGivenToParticipants: ["Certificate", "Startup Kit", "Investor Contacts"],
    about: "Startup Pitch Fest is an exciting opportunity for entrepreneurs to pitch their startup ideas to investors and receive mentorship, funding, and exposure."
  },
  {
    name: "Code Battle 2025",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpMcnfYdvbkHeFFpjfUkglr8-kxv3Uty66vQ&s",
    description: "A coding competition for developers to solve challenging problems.",
    venue: "TechHub, Bangalore",
    time: "10:00 AM - 8:00 PM",
    conductedBy: "Code Club",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "₹300",
    lastDateToRegister: "2025-01-15",
    eventDate: "2025-01-30",
    prize: "₹25,000 Cash Prize + Gadgets",
    thingsGivenToParticipants: ["Certificate", "Trophy for Winners", "Swag Kit"],
    about: "Code Battle 2025 is a high-energy coding competition where developers race against time to solve complex algorithmic challenges."
  },
  {
    name: "Photography Contest",
    image: "https://cdn2.allevents.in/thumbs/thumb6774017ececeb.jpg",
    description: "Capture the best moments and showcase your photography skills.",
    venue: "City Park, Bangalore",
    time: "8:00 AM - 4:00 PM",
    conductedBy: "Photo Enthusiasts Club",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "Free",
    lastDateToRegister: "2025-01-22",
    eventDate: "2025-02-08",
    prize: "Camera Equipment Worth ₹50,000",
    thingsGivenToParticipants: ["Certificate", "Photography Workshop Pass"],
    about: "The Photography Contest is an opportunity for budding photographers to showcase their talent and win prizes while learning new techniques at workshops."
  },
  {
    name: "TechSpark 2025",
    image: "https://amcec.edu.in/wp-content/uploads/2022/07/IEEE.jpeg",
    description: "A technology hackathon focusing on innovative software solutions.",
    venue: "ICAT Design and Media College, Bangalore",
    time: "10:00 AM - 6:00 PM",
    conductedBy: "Tech Society",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "Free",
    lastDateToRegister: "2025-01-20",
    eventDate: "2025-02-05",
    prize: "₹50,000 Cash Prize + Internship Opportunity",
    thingsGivenToParticipants: ["Certificate of Participation", "T-Shirts", "Goodie Bags"],
    about: "TechSpark 2025 is an innovative tech hackathon where developers, engineers, and tech enthusiasts come together to solve real-world problems and showcase their creativity."
  },
  {
    name: "Art Fiesta 2025",
    image: "https://cdn-az.allevents.in/events9/banners/5f5e8d972d99b879e5e86637f8a976160a365f4c62cf9bf3395aed8f6bfd289e-rimg-w1200-h675-dc1f4665-gmir?v=1728589379",
    description: "A creative art competition where participants can showcase their artistic skills.",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    venue: "National Art Gallery, Bangalore",
    time: "11:00 AM - 5:00 PM",
    conductedBy: "Art Lovers Association",
    entryFee: "₹200",
    lastDateToRegister: "2025-01-18",
    eventDate: "2025-02-01",
    prize: "₹10,000 Cash Prize + Art Supplies",
    thingsGivenToParticipants: ["Certificate", "Art Supplies Kit"],
    about: "Art Fiesta 2025 is an artistic celebration where participants can express their creativity through painting, drawing, sculpture, and other art forms."
  },
  {
    name: "Startup Pitch Fest",
    image: "https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/mobile_banner/659d840d2f97e_mega-startup-pitch-day-and-expo-24.png?d=700x400",
    description: "An event for aspiring entrepreneurs to pitch their ideas to investors.",
    venue: "Bangalore Tech Park",
    time: "9:00 AM - 4:00 PM",
    conductedBy: "Startup Network",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "₹500",
    lastDateToRegister: "2025-01-25",
    eventDate: "2025-02-10",
    prize: "Funding Opportunity + Incubation Support",
    thingsGivenToParticipants: ["Certificate", "Startup Kit", "Investor Contacts"],
    about: "Startup Pitch Fest is an exciting opportunity for entrepreneurs to pitch their startup ideas to investors and receive mentorship, funding, and exposure."
  },
  {
    name: "Code Battle 2025",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpMcnfYdvbkHeFFpjfUkglr8-kxv3Uty66vQ&s",
    description: "A coding competition for developers to solve challenging problems.",
    venue: "TechHub, Bangalore",
    time: "10:00 AM - 8:00 PM",
    conductedBy: "Code Club",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "₹300",
    lastDateToRegister: "2025-01-15",
    eventDate: "2025-01-30",
    prize: "₹25,000 Cash Prize + Gadgets",
    thingsGivenToParticipants: ["Certificate", "Trophy for Winners", "Swag Kit"],
    about: "Code Battle 2025 is a high-energy coding competition where developers race against time to solve complex algorithmic challenges."
  },
  {
    name: "Photography Contest",
    image: "https://cdn2.allevents.in/thumbs/thumb6774017ececeb.jpg",
    description: "Capture the best moments and showcase your photography skills.",
    venue: "City Park, Bangalore",
    time: "8:00 AM - 4:00 PM",
    conductedBy: "Photo Enthusiasts Club",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "Free",
    lastDateToRegister: "2025-01-22",
    eventDate: "2025-02-08",
    prize: "Camera Equipment Worth ₹50,000",
    thingsGivenToParticipants: ["Certificate", "Photography Workshop Pass"],
    about: "The Photography Contest is an opportunity for budding photographers to showcase their talent and win prizes while learning new techniques at workshops."
  },
  {
    name: "TechSpark 2025",
    image: "https://amcec.edu.in/wp-content/uploads/2022/07/IEEE.jpeg",
    description: "A technology hackathon focusing on innovative software solutions.",
    venue: "ICAT Design and Media College, Bangalore",
    time: "10:00 AM - 6:00 PM",
    conductedBy: "Tech Society",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "Free",
    lastDateToRegister: "2025-01-20",
    eventDate: "2025-02-05",
    prize: "₹50,000 Cash Prize + Internship Opportunity",
    thingsGivenToParticipants: ["Certificate of Participation", "T-Shirts", "Goodie Bags"],
    about: "TechSpark 2025 is an innovative tech hackathon where developers, engineers, and tech enthusiasts come together to solve real-world problems and showcase their creativity."
  },
  {
    name: "Art Fiesta 2025",
    image: "https://cdn-az.allevents.in/events9/banners/5f5e8d972d99b879e5e86637f8a976160a365f4c62cf9bf3395aed8f6bfd289e-rimg-w1200-h675-dc1f4665-gmir?v=1728589379",
    description: "A creative art competition where participants can showcase their artistic skills.",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    venue: "National Art Gallery, Bangalore",
    time: "11:00 AM - 5:00 PM",
    conductedBy: "Art Lovers Association",
    entryFee: "₹200",
    lastDateToRegister: "2025-01-18",
    eventDate: "2025-02-01",
    prize: "₹10,000 Cash Prize + Art Supplies",
    thingsGivenToParticipants: ["Certificate", "Art Supplies Kit"],
    about: "Art Fiesta 2025 is an artistic celebration where participants can express their creativity through painting, drawing, sculpture, and other art forms."
  },
  {
    name: "Startup Pitch Fest",
    image: "https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/mobile_banner/659d840d2f97e_mega-startup-pitch-day-and-expo-24.png?d=700x400",
    description: "An event for aspiring entrepreneurs to pitch their ideas to investors.",
    venue: "Bangalore Tech Park",
    time: "9:00 AM - 4:00 PM",
    conductedBy: "Startup Network",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "₹500",
    lastDateToRegister: "2025-01-25",
    eventDate: "2025-02-10",
    prize: "Funding Opportunity + Incubation Support",
    thingsGivenToParticipants: ["Certificate", "Startup Kit", "Investor Contacts"],
    about: "Startup Pitch Fest is an exciting opportunity for entrepreneurs to pitch their startup ideas to investors and receive mentorship, funding, and exposure."
  },
  {
    name: "Code Battle 2025",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpMcnfYdvbkHeFFpjfUkglr8-kxv3Uty66vQ&s",
    description: "A coding competition for developers to solve challenging problems.",
    venue: "TechHub, Bangalore",
    time: "10:00 AM - 8:00 PM",
    conductedBy: "Code Club",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "₹300",
    lastDateToRegister: "2025-01-15",
    eventDate: "2025-01-30",
    prize: "₹25,000 Cash Prize + Gadgets",
    thingsGivenToParticipants: ["Certificate", "Trophy for Winners", "Swag Kit"],
    about: "Code Battle 2025 is a high-energy coding competition where developers race against time to solve complex algorithmic challenges."
  },
  {
    name: "Photography Contest",
    image: "https://cdn2.allevents.in/thumbs/thumb6774017ececeb.jpg",
    description: "Capture the best moments and showcase your photography skills.",
    venue: "City Park, Bangalore",
    time: "8:00 AM - 4:00 PM",
    conductedBy: "Photo Enthusiasts Club",
    hostImage:"https://upload.wikimedia.org/wikipedia/commons/b/be/Icat_logo.png",
    duration:"2hrs 30min",
    category:"Tech Talks",
    entryFee: "Free",
    lastDateToRegister: "2025-01-22",
    eventDate: "2025-02-08",
    prize: "Camera Equipment Worth ₹50,000",
    thingsGivenToParticipants: ["Certificate", "Photography Workshop Pass"],
    about: "The Photography Contest is an opportunity for budding photographers to showcase their talent and win prizes while learning new techniques at workshops."
  }
];

export default events;
